spring:
  datasource:
    driver className: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: ${MYSQL_HOST}
    port: 15498
    password: ${REDIS_PASSWORD}
flyway.locations.filesystem: db/migration
jwt:
  secret: secret
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health, prometheus'